# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_analysis_categoryanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryanalysis',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='web.Analysis'),
        ),
        migrations.AlterField(
            model_name='categoryanalysis',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Category'),
        ),
    ]
