# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_analysed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
